    import { StyleSheet } from "react-native";

    export default StyleSheet.create({
    container: {
        flex: 1,
        padding: 50,
        backgroundColor: "#f1f2f6",
    },
    title: {
        fontSize: 32,
        fontWeight: "bold",
        color: "#ca373cff",
        textShadowColor: "rgba(0, 0, 0, 0.2)",
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
        textAlign: "center",
        marginBottom: 30,
    },
    subtitle: {
        fontSize: 16,
        color: "#666",
        fontStyle: "italic",
        textAlign: "center",
        marginBottom: 30,
    },
    statsContainer: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginBottom: 30,
        backgroundColor: "white",
        borderRadius: 10,
        padding: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    statItem: {
        alignItems: "center",
    },
    statNumber: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#4ecdc4",
    },
    statLabel: {
        fontSize: 14,
        color: "#666",
    },
    input: {
        borderWidth: 1,
        borderColor: "#ddd",
        padding: 12,
        marginBottom: 10,
        borderRadius: 8,
        backgroundColor: "#f9f9f9",
    },
    formContainer: {
        backgroundColor: "white",
        padding: 15,
        borderRadius: 10,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    formTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 10,
        color: "#444",
        textAlign: "center",
    },
    formButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    formButton: {
        padding: 12,
        borderRadius: 8,
        minWidth: 100,
        alignItems: "center",
    },
    cancelButton: {
        backgroundColor: "#999",
    },
    addButtonForm: {
        backgroundColor: "#ff6b6b",
    },
    formButtonText: {
        color: "white",
        fontWeight: "bold",
    },
    card: {
        padding: 15,
        marginBottom: 15,
        borderRadius: 12,
        width: "48%",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    caughtCard: {
        borderWidth: 3,
        borderColor: 'gold',
        opacity: 0.9,
    },
    cardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        alignItems: "center",
        marginBottom: 10,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: "bold",
    },
    whiteText: {
        color: "white",
        textShadowColor: "rgba(0, 0, 0, 0.3)",
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
    statusIndicator: {
        padding: 4,
        borderRadius: 12,
    },
    caughtIndicator: {
        backgroundColor: "rgba(0, 0, 0, 0.2)",
    },
    freeIndicator: {
        backgroundColor: "rgba(255, 255, 255, 0.3)",
    },
    statusText: {
        fontSize: 12,
    },
    imageContainer: {
        backgroundColor: "rgba(255, 255, 255, 0.3)",
        borderRadius: 50,
        padding: 10,
        marginBottom: 10,
        width: 100,
        height: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    image: {
        width: 80,
        height: 80,
        resizeMode: "contain",
    },
    typeContainer: {
        backgroundColor: "rgba(0, 0, 0, 0.2)",
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        marginBottom: 10,
    },
    typeText: {
        fontSize: 12,
        fontWeight: "bold",
    },
    catchButton: {
        backgroundColor: "rgba(255, 255, 255, 0.8)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    caughtButton: {
        backgroundColor: "rgba(0, 0, 0, 0.2)",
    },
    catchButtonText: {
        color: "#333",
        fontSize: 12,
        fontWeight: "bold",
    },
    row: {
        justifyContent: "space-between",
    },
    listContent: {
        paddingBottom: 20,
    },
    modalContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
        backgroundColor: "white",
        padding: 20,
        borderRadius: 15,
        alignItems: "center",
        width: "80%",
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: "bold",
        marginBottom: 15,
        color: "#333",
    },
    modalImage: {
        width: 150,
        height: 150,
        resizeMode: "contain",
        marginBottom: 15,
    },
    modalType: {
        fontSize: 16,
        marginBottom: 30,
        color: "#666",
    },
    modalStatus: {
        fontSize: 16,
        marginBottom: 10,
        fontWeight: "bold",
    },
    modalButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
    },
    modalButton: {
        padding: 10,
        borderRadius: 8,
        minWidth: 100,
        alignItems: "center",
    },
    modalCatchButton: {
        backgroundColor: "#ff6b6b",
    },
    modalReleaseButton: {
        backgroundColor: "#4ecdc4",
    },
    modalCloseButton: {
        backgroundColor: "#999",
    },
    modalButtonText: {
        color: "white",
        fontWeight: "bold",
    },
    addButton: {
        backgroundColor: "#ff6b6b",
        padding: 15,
        borderRadius: 10,
        alignItems: "center",
        marginBottom: 20,
    },
    addButtonText: {
        color: "white",
        fontWeight: "bold",
        fontSize: 16,
    },
        placeholderContainer: {
        width: 80,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.1)',
        borderRadius: 8,
    },
    placeholderText: {
        color: 'white',
        fontSize: 10,
        textAlign: 'center',
        }, 
    modalImageContainer: {
        width: 200,
        height: 200,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f0f0f0',
        borderRadius: 10,
        marginBottom: 15,
    },
    modalImage: {
        width: 180,
        height: 180,
        resizeMode: "contain",
    },
    deleteButton: {
        position: 'absolute',
        top: 0,
        right: 0,
        borderRadius: 10,
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 5,
    },
    deleteButtonText: {
        color: 'white',
        fontSize: 8,
        fontWeight: 'bold',
    },
    });